### ISSUE TITLE
Adding conan support

### ISSUE THREAD

**Issue by Fohlen** [cbbowen/graph#8]
Hello there. It would be nice to have [conan](https://conan.io/) support. If you would like I can create a PR to set it up.

**Comment by cbbowen** [comment]
I added experimental support in 986bb2c767896a6d8d4396ae319a2bd00206571b.  It seems to work, but I don't use Conan myself, so I'd welcome any feedback.

**Comment by Fohlen** [comment]
@cbbowen nice! Thanks for the fast reaction. I have tested installation under OSX and it appears to work just fine. I will add a `test_package` PR to check whether it works as supposed. So the to-do list here is

- [x] add a `test_package`
- [ ] tag a release version, e.g `0.1`
- [x] if wanted one can easily add a CI, https://github.com/bincrafters/conan-templates
  - [ ] if CI is desired, add Travis and AppVeyor badge
- [ ] upload a version of `graph/0.1.0@cbbowen/testing`

**Comment by Fohlen** [comment]
This was done
